#!/usr/bin/env python3
"""
GDExtension Header Generator
Scans src/ for headers using GD_GENERATED_BODY() and GDPROPERTY() annotations,
then generates .gen.h (GD_GENERATED_BODY macro redefinition) and .gen.cpp (implementations).

Run manually:   python tools/gdheader_gen.py
Runs automatically via SConstruct on every build.
"""

import re
import os
from dataclasses import dataclass

# Maps C++ types to Godot Variant::Type enum values
TYPE_MAP = {
    'float':   'FLOAT',
    'double':  'FLOAT',
    'int':     'INT',
    'bool':    'BOOL',
    'String':  'STRING',
    'Vector2': 'VECTOR2',
    'Vector3': 'VECTOR3',
    'Color':   'COLOR',
}

@dataclass
class ParsedHeader:
    class_name: str
    parent_name: str
    properties: list
    functions: list
    signals: list

def parse_header(filepath):
    """Parse a header file for GD annotations."""
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    if 'GD_GENERATED_BODY' not in content:
        return None
    class_match = re.search(r'class\s+(\w+)\s*:\s*public\s+(\w+)[^;]*\{', content)
    if not class_match:
        return None
    class_name = class_match.group(1)
    parent_name = class_match.group(2)
    prop_re = re.compile(r'GDPROPERTY\s*\(\s*\)\s+(\w+)\s+(\w+)\s*;')
    properties = prop_re.findall(content)
    func_re = re.compile(r'GDFUNCTION\s*\(\s*\)\s+(\w+)\s+(\w+)\s*\(([^)]*)\)\s*;')
    functions = func_re.findall(content)
    signal_re = re.compile(r'GDSIGNAL\s*\(\s*"([^"]+)"\s*,([^)]*)\)')
    signals = signal_re.findall(content)
    return ParsedHeader(class_name, parent_name, properties, functions, signals)

def ensure_gen_include(filepath, base_name, rel_dir):
    """Auto-insert #include "generated/xxx.gen.h" after the last #include, if not already present."""
    # Normalize rel_dir: '.' means root, so don't add extra directory level
    include_path = f'generated/{rel_dir}/{base_name}.gen.h' if rel_dir != '.' else f'generated/{base_name}.gen.h'
    gen_include = f'#include "{include_path}"'
    with open(filepath, encoding='utf-8') as f:
        lines = f.readlines()
    if any(gen_include in line for line in lines):
        return
    insert_pos = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith('#include'):
            insert_pos = i + 1
        if stripped.startswith('namespace') or re.match(r'class\s+\w+', stripped):
            break
    lines.insert(insert_pos, gen_include + '\n')
    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    print(f'[gdheader_gen] Inserted {gen_include} into {os.path.basename(filepath)}')

def build_method_params_string(parameters_array):
    params = []
    for raw_parameter in parameters_array.split(','):
        parts = raw_parameter.strip().split()
        if len(parts) == 2:
            params.append(f'"{parts[1]}"')
    params_string = ', '.join(params)
    if params:
        params_string = ', ' + params_string
    return params_string

def build_signal_params_string(parameters_array):
    types = []
    names = []
    params_string = ''
    for i, raw_parameter in enumerate(parameters_array.split(',')):
        if i % 2 == 0:
            types.append(raw_parameter.strip())
        else:
            names.append(raw_parameter.strip())
    for i, type in enumerate(types):
        variant_type = TYPE_MAP.get(type, 'NIL')
        name = names[i] if i < len(names) else f'param{i}'
        params_string += f', PropertyInfo(Variant::{variant_type}, "{name}")'
    return params_string

def write_gen_h(parsed: ParsedHeader, out_dir, base_name, subdir):
    """Write .gen.h file with macro definitions, preserving source directory structure."""
    macro_lines = [
        f'    GDCLASS({parsed.class_name}, {parsed.parent_name})',
        'protected:',
        '    static void _bind_methods();',
    ]
    if parsed.properties:
        macro_lines.append('public:')
        for cpp_type, prop_name in parsed.properties:
            macro_lines.append(f'    {cpp_type} get_{prop_name}() const;')
            macro_lines.append(f'    void set_{prop_name}({cpp_type} val);')
    
    # Build macro body with proper line continuations
    macro_body_lines = []
    for i, line in enumerate(macro_lines):
        if i < len(macro_lines) - 1:
            macro_body_lines.append(line + ' \\')
        else:
            macro_body_lines.append(line)
    
    gen_h_content = (
        '// AUTO-GENERATED by tools/gdheader_gen.py — do not edit\n'
        '#undef GD_GENERATED_BODY\n'
        '#define GD_GENERATED_BODY() \\\n' +
        '\n'.join(macro_body_lines) + '\n'
    )
    
    # Handle root-level files: don't add '.' to path
    gen_h_path = os.path.join(out_dir, subdir, f'{base_name}.gen.h').replace('\\', '/') if subdir != '.' else os.path.join(out_dir, f'{base_name}.gen.h').replace('\\', '/')
    os.makedirs(os.path.dirname(gen_h_path), exist_ok=True)
    with open(gen_h_path, 'w', encoding='utf-8') as f:
        f.write(gen_h_content)

def write_gen_cpp(parsed: ParsedHeader, out_dir, base_name, header_include, subdir):
    """Write .gen.cpp file with implementations, preserving source directory structure."""
    lines_cpp = [
        f'// AUTO-GENERATED by tools/gdheader_gen.py — do not edit\n',
        f'#include "{header_include}"\n',
        f'#include "internal/class_registry.h"\n',
        f'\n',
        f'using namespace godot;\n',
        f'\n',
    ]
    for cpp_type, prop_name in parsed.properties:
        lines_cpp.append(f'{cpp_type} {parsed.class_name}::get_{prop_name}() const {{ return {prop_name}; }}\n')
        lines_cpp.append(f'void {parsed.class_name}::set_{prop_name}({cpp_type} val) {{ {prop_name} = val; }}\n')
    if parsed.properties:
        lines_cpp.append('\n')
    lines_cpp.append(f'void {parsed.class_name}::_bind_methods() {{\n')
    for cpp_type, prop_name in parsed.properties:
        variant_type = TYPE_MAP.get(cpp_type, 'NIL')
        lines_cpp.append(f'    ClassDB::bind_method(D_METHOD("get_{prop_name}"), &{parsed.class_name}::get_{prop_name});\n')
        lines_cpp.append(f'    ClassDB::bind_method(D_METHOD("set_{prop_name}", "{prop_name}"), &{parsed.class_name}::set_{prop_name});\n')
        lines_cpp.append(f'    ADD_PROPERTY(PropertyInfo(Variant::{variant_type}, "{prop_name}"), "set_{prop_name}", "get_{prop_name}");\n')
    for signal_name, signal_parameters in parsed.signals:
        lines_cpp.append(f'    ADD_SIGNAL(MethodInfo("{signal_name}"{build_signal_params_string(signal_parameters)}));\n')
    for _, method_name, parameters in parsed.functions:
        lines_cpp.append(f'    ClassDB::bind_method(D_METHOD("{method_name}"{build_method_params_string(parameters)}), &{parsed.class_name}::{method_name});\n')
    lines_cpp.append('}\n\n')
    lines_cpp.append(
        f'namespace {{\n'
        f'    bool _registered_{parsed.class_name} = []() {{\n'
        f'        godot::ClassRegistry::get().add([]() {{ GDREGISTER_CLASS({parsed.class_name}); }});\n'
        f'        return true;\n'
        f'    }}();\n'
        f'}}\n'
    )
    # Handle root-level files: don't add '.' to path
    gen_cpp_path = os.path.join(out_dir, subdir, f'{base_name}.gen.cpp').replace('\\', '/') if subdir != '.' else os.path.join(out_dir, f'{base_name}.gen.cpp').replace('\\', '/')
    os.makedirs(os.path.dirname(gen_cpp_path), exist_ok=True)
    with open(gen_cpp_path, 'w', encoding='utf-8') as f:
        f.writelines(lines_cpp)

def generate(src_dir, out_dir):
    """Generate .gen.h and .gen.cpp files for all annotated classes, preserving directory structure."""
    os.makedirs(out_dir, exist_ok=True)
    for root, dirs, files in os.walk(src_dir):
        for filename in files:
            if not filename.endswith('.h') or filename.endswith('.gen.h'):
                continue
            filepath = os.path.join(root, filename)
            parsed = parse_header(filepath)
            if not parsed:
                continue
            base_name = os.path.splitext(filename)[0]
            
            # Compute relative directory path from src_dir to preserve in generated files
            rel_dir = os.path.relpath(os.path.dirname(filepath), src_dir).replace('\\', '/')
            
            ensure_gen_include(filepath, base_name, rel_dir)
            write_gen_h(parsed, out_dir, base_name, rel_dir)
            
            # Header include path for .gen.cpp (back to source)
            header_include = os.path.relpath(filepath, src_dir).replace('\\', '/')
            write_gen_cpp(parsed, out_dir, base_name, header_include, rel_dir)
            
            props_info = f'{len(parsed.properties)} propert{"y" if len(parsed.properties) == 1 else "ies"}' if parsed.properties else 'no properties'
            output_path = f'generated/{rel_dir}/{base_name}.gen.h' if rel_dir != '.' else f'generated/{base_name}.gen.h'
            print(f'[gdheader_gen] {parsed.class_name} ({props_info}) -> {output_path} / .gen.cpp')

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(script_dir, '..', 'src')
    out_dir = os.path.join(src_dir, 'generated')
    generate(src_dir, out_dir)
